// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD-7E6uqiTC4nHaebHQdGeWULBC2Dv2i8',
    appId: '1:1008902256725:web:e0082041ad39d483783cdc',
    messagingSenderId: '1008902256725',
    projectId: 'menumate-13c03',
    authDomain: 'menumate-13c03.firebaseapp.com',
    storageBucket: 'menumate-13c03.appspot.com',
    measurementId: 'G-LCWXEW0VJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB351wf2QH4QY9FQI1mVXielZwvzC0DB4c',
    appId: '1:1008902256725:android:3608d6e02de539b3783cdc',
    messagingSenderId: '1008902256725',
    projectId: 'menumate-13c03',
    storageBucket: 'menumate-13c03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP7qLY6ZVX4OstEli0PwbXIOWZ_gJMYe4',
    appId: '1:1008902256725:ios:f214ac5b4a6ae948783cdc',
    messagingSenderId: '1008902256725',
    projectId: 'menumate-13c03',
    storageBucket: 'menumate-13c03.appspot.com',
    iosBundleId: 'com.menumate.menumate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP7qLY6ZVX4OstEli0PwbXIOWZ_gJMYe4',
    appId: '1:1008902256725:ios:f214ac5b4a6ae948783cdc',
    messagingSenderId: '1008902256725',
    projectId: 'menumate-13c03',
    storageBucket: 'menumate-13c03.appspot.com',
    iosBundleId: 'com.menumate.menumate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD-7E6uqiTC4nHaebHQdGeWULBC2Dv2i8',
    appId: '1:1008902256725:web:450ae8ec5b63d113783cdc',
    messagingSenderId: '1008902256725',
    projectId: 'menumate-13c03',
    authDomain: 'menumate-13c03.firebaseapp.com',
    storageBucket: 'menumate-13c03.appspot.com',
    measurementId: 'G-02M2XQD5S0',
  );
}
